### ISSUE TITLE
FPT and VTC not working

### ISSUE THREAD

**Issue by anhstar** [zecoj/kodi-tvvn#1]
Hello,
Just want to say thank you first for this great addon.
Secondly, the FPT's source and VTC's source are both down.
Can you have a look when you have the time please?
Thank you

**Comment by zecoj** [comment]
I'm aware of the issue. To fix FPT source, you can change line 180 in tvvn.py to:
req = urllib2.Request(url, post_data, {'X-Requested-With':'XMLHttpRequest'})

I'll release a fix to VTC soon-ish.

**Comment by anhstar** [comment]
Thank you very much it works :)
