### ISSUE TITLE
Workaround: Python 3 and "TV Viet Nam"

### ISSUE THREAD

**Issue by meltmelt** [zecoj/kodi-tvvn#8]
Since **Python 2.x** has reached end of life, the support for legacy add-ons has been dropped from **Kodi v19 "Matrix"**.
The addon sadly doesn't work at the moment.

More in depth info here:
https://kodi.tv/article/kodi-broke-my-addons

**Workaround**
Until the addon is rewritten, you can get it working again by downgrading back to **Kodi v18 "Leia"**.

The older Kodi v18 "Leia" release available here for your plattform:
https://mirrors.kodi.tv/releases/

If you are on Android, remember to turn off "auto update" for Kodi in Google Play store. Otherwise it will be updated and be broken again.

Sharing this solution since my dad uses this addon on a daily basis. Big thanks to you, the addon author, anh Ben!

**Comment by zecoj** [comment]
Thanks @meltmelt. I've updated the code to Python 3. Will try to create pull request to official repo soon; for now, you can download and replace the files manually.
